### ISSUE TITLE
Automated CKAN Job Error Condition ckeck-stuck-jobs

### ISSUE THREAD

**Issue by btylerburton** [GSA/catalog.data.gov#1471]
Workflow with Issue: 4 - Automated CKAN Jobs
Job Failed: ckan-auto-command
CKAN Command (in question): ckan geodatagov check-stuck-jobs
CKAN Command Schedule: 30 6 * * *
Cloud.gov Environment: prod

Last Commit: 3a7d473b536c442625bc043dfd64566c6e2f9e71
Number of times run: 1
Last run by: btylerburton
Github Action Run: https://github.com/GSA/catalog.data.gov/actions/runs/11379675273

**Comment by btylerburton** [comment]
@FuhuXia forgot to check in with you on this before EOD.

I ran the query suggested here:
https://github.com/GSA/data.gov/wiki/Stuck-Harvest-Fix#understanding-what-is-stuck

   title   |  state   | count |        last_fetched        |       last_gathered        
-----------+----------+-------+----------------------------+----------------------------
 NOS NCCOS | COMPLETE |   715 | 2024-10-15 11:55:58.666356 | 2024-10-15 11:52:36.84156
 NOS NCCOS | IMPORT   |     1 | 2024-10-15 12:30:34.438465 | 2024-10-15 11:52:31.863972
 NOS NCCOS | ERROR    |     1 | 2024-10-15 12:50:20.532944 | 2024-10-15 11:52:27.639643
(3 rows)

Then the second query get harvest_job_id:
https://github.com/GSA/data.gov/wiki/Stuck-Harvest-Fix#get-harvest_job_ids-for-running-jobs

    title   |  state   |            harvest_job_id            | count 
-----------+----------+--------------------------------------+-------
 NOS NCCOS | COMPLETE | 1fa5f8e2-519b-41b5-9b43-5fd532de1198 |   715
 NOS NCCOS | ERROR    | 1fa5f8e2-519b-41b5-9b43-5fd532de1198 |     1
 NOS NCCOS | IMPORT   | 1fa5f8e2-519b-41b5-9b43-5fd532de1198 |     1
(3 rows)

Not sure what to do to clear out these jobs after that.

**Comment by FuhuXia** [comment]
It was force finished by the GH actions a few hours ago since it has passed 72 hours.

I would look at the catalog-gather log to see what happens to this source and this job, and usually manually stop and job on the UI and reharvest it again to see if we can replicate it.

You can see this source was going thru some major change, all existing xml files were deleted and about same amount of new xml files was freshly added.
