### ISSUE TITLE
Test DCAT-US harvest from sources using collections

### ISSUE THREAD

**Issue by avdata99** [GSA/catalog.data.gov#41]
One difference between harvest upstream version and the GSA fork is that [the fork changes the order in which we harvest](https://github.com/GSA/ckanext-harvest/commit/1f8e9138d92c8ac7504c35fad980c76667267689). 

The DCAT-US harvester adds [datajson_collection](https://github.com/GSA/ckanext-datajson/blob/f4ac11c2d2041e64f8ec3976bd2df73511abda68/ckanext/datajson/harvester_base.py#L213) to source config to be used at the harvester ext to divide the harvest process [first for parents and then for children](https://github.com/GSA/ckanext-harvest/blob/bb4219462483029fd0b0d7a06403029987f38e89/ckanext/harvest/logic/action/update.py#L531). 
First, we harvest _father_ datasets and then the children.

[We already have a test case for DCAT-US with collections](https://github.com/GSA/ckanext-geodatagov/pull/131) but this test does not cover this feature.

## Tasks
 - [x] Add test case for DCAT-US collection with multiple unordered datasets. 
 - [x] Fix it if is required

Related to #40 and [Multi#301](https://github.com/GSA/datagov-ckan-multi/issues/301)

**Comment by adborden** [comment]
FWIW, I am not a fan of the two-phase harvest. It's confusing and error prone. There's also no support for it in the UI, so from a user perspective, it's completely opaque.

A while back, I started on a draft of how to refactor ckanext-datajson https://gist.github.com/adborden/ec2c7a1b315177eacd43624b733d351c. It's not complete, but worth a look.
