### ISSUE TITLE
Bug: Harvest source importer misses some metadata

### ISSUE THREAD

**Issue by avdata99** [GSA/catalog.data.gov#42]
## Bug report
Expected Behavior

Actual Behavior

## Details/Tasks
- Related to [#302](https://github.com/GSA/datagov-ckan-multi/issues/302) and [#312](https://github.com/GSA/datagov-ckan-multi/issues/312)

## Acceptance Criteria
After we import harvest sources we need to validate we have all the information we expect
 - [x] Check if we have the same config as the original source (sometimes the config come as _extras_)
 - [x] Check if we have the same extras as the original source (if we detect _config_ inside _extras_ we move it to config and remove from extras)
 - [x] Check the organization is the same and has the same image included.
 - [x] in the old/classic catalog app (with CKAN 2.3) when we create a harvest soure we need to pick federal or not-federal source. This info seems not been captured while we import. Is this private data?: **No, this info is saved as validator_schema in extra['config']. If validator_schema is empty the source is federal** 

At the [final report](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=1667396946) about harvest sources in the new catalog we found some error that make us think that we fail while import this harfest sources.

Some sources faileds with validation errors:

| source     | url | config | added | updated | nulls | errors | 
|------------- | --- | -------- | --------- | ---------- | ------- | ------- | 
epa-sciencehub | https://pasteur.epa.gov/metadata.json | {"private_datasets": "False"} | 1665 | 0 | -1 | Title: EPA True NO2 ground site measurements. 1 Error(s) Found. ### ERROR 1: 'distribution':[{'accessURL': 'http://www-air.larc.nasa.gov/cgi-bin/ArcView/disco ...
mcc-data-json | https://data.mcc.gov/data.json | {"private_datasets": "False"} | 199 | 0 | -1 | Title: Ghana - Agriculture - Land Tenure; 1 Error(s) Found. ### ERROR 1: 'distribution':[{'downloadURL': 'http://microdata.worldbank.org/index.php/cata ...
healthdata-gov | https://healthdata.gov/data.json | {"private_datasets": "False"} | 410 | 0 | 1302 | Title: Commercial Medical Insurance 1 Error(s) Found. ### ERROR 1: 'references':['https://wwwdev.cdc.gov/visionhealth/vehss/data/claims/marketscan.html; https://marketscan.truvenhealth.com/marketscanportal/'] is not valid under any of the given schemas ...
energystar | http://data.energystar.gov/data.json | {"private_datasets": "False"} | 54 | 0 | -1 | Title: ENERGY STAR Certified Ceiling Fans Light Kits; 1 Error(s) Found. ### ERROR 1: 'keyword' is a required proper ...

**Comment by kimwdavidson** [comment]
Andres to connect PR, add QA steps with links

**Comment by avdata99** [comment]
For QA this issue we need to run the import command in the sandbox and check that the sources and organizations are complete imported.

For example:
´´´
python import_harvest_sources.py --source_ty=datajson --limit=3 --destination_api_key=xxx
´´´

Check we have:
 - harvest source extras
 - organization extras
 - organization image
 - any other feature visible at catalog.data.gov

**Comment by adborden** [comment]
@avdata99 not sure what I'm looking at... the command finds 3 sources and fails on all three. Why are we expecting an error here?

```
        ERROR status: 500
         content:b'{"help": "https://catalog-next.sandbox.datagov.us/api/3/action/help_show?name=harvest_source_update", "success": false, "error": {"message": "Internal Server Error", "__type": "Internal Server Error"}}'
        ERROR status: 500
         content:b'{"help": "https://catalog-next.sandbox.datagov.us/api/3/action/help_show?name=harvest_source_update", "success": false, "error": {"message": "Internal Server Error", "__type": "Internal Server Error"}}'
        ERROR status: 409
         content:b'{"help": "https://catalog-next.sandbox.datagov.us/api/3/action/help_show?name=harvest_source_create", "success": false, "error": {"name": ["Missing value"], "url": ["Missing value"], "title": ["Missing value"], "owner_org": ["An organization must be provided", "Missing value"], "source_type": ["Missing value"], "__type": "Validation Error"}}'
```

**Comment by avdata99** [comment]
@adborden sorry, the [PR](https://github.com/GSA/catalog.data.gov/pull/80) is still open. I need a second review because we found some errors related to #75. I moved this to _in progress_, will be ready to QA tomorrow. If you want to try this you can use the `allow_list_while_import` branch.

**Comment by thejuliekramer** [comment]
@adborden this is ready to test again

**Comment by adborden** [comment]
QA'd on sandbox.

    $ pipenv run python import_harvest_sources.py     --source_ty=datajson     --limit=3     --destination_url=https://catalog-next.sandbox.datagov.us     --destination_api_key=$CKAN_API_KEY

This one gave a 500 error, should I open an issue?
https://catalog.data.gov/api/3/action/harvest_source_show?id=11cd07d8-f5a7-4207-9852-6160e09ff240

**Comment by avdata99** [comment]
You can create a new issue @adborden but as a part of [Multi#355](https://github.com/GSA/datagov-ckan-multi/issues/355) we are going to import sources and add new issues if necessary.
