### ISSUE TITLE
Recover hidden code at Theme

### ISSUE THREAD

**Issue by avdata99** [GSA/catalog.data.gov#50]
The DataGovTheme depends on `ckanext-archiver` and `ckanext-qa` and uses its helpers:
 - [archiver_is_resource_broken_line](https://github.com/GSA/ckanext-archiver/blob/datagov/ckanext/archiver/helpers.py#L19) from `archiver`
 - [qa_openness_stars_resource_table](https://github.com/GSA/ckanext-qa/blob/datagov/ckanext/qa/helpers.py#L44) from `qa`

Since this new catalog move extension to the upstream version we miss these functions and the Theme is not able to show resources inside datasets.

We hide these calls in a [PR](https://github.com/GSA/ckanext-datagovtheme/pull/43).

This issue is to validate if we want these features and recover them.
Related issues:
 - [#1690](https://github.com/GSA/datagov-deploy/issues/1690)
 - [#46](https://github.com/GSA/catalog.data.gov/issues/46)

Should be part of the analysis at:
 - [#1426 Upgrade Arvhiver issue](https://github.com/GSA/datagov-deploy/issues/1426)
 - [#1415 Upgrade QA issue](https://github.com/GSA/datagov-deploy/issues/1415)

**Comment by avdata99** [comment]
Reopen since we will need to update this in the new catalog in the future

**Comment by thejuliekramer** [comment]
@avdata99 for the method `qa_openness_stars_resource_table` we can replace with the new method `qa_openness_stars_resource_html` in the upstream [helpers.py](https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/helpers.py)

**Comment by thejuliekramer** [comment]
@avdata99 same goes for `archiver_is_resource_broken_line` we can replace with `archiver_is_resource_broken_html` in the upstream helpers.py https://github.com/ckan/ckanext-archiver/blob/master/ckanext/archiver/helpers.py#L9

**Comment by cmugisha** [comment]
@avdata99 I just realized that this ticket doesn't have an estimate. Could you add it? Thanks!

**Comment by avdata99** [comment]
How to QA:
This issue is because we hide the UI parts that we ask in [Multi#391](https://github.com/GSA/datagov-ckan-multi/issues/391) so if 391 is QA'd this could be considered OK

**Comment by avdata99** [comment]
Before QA is required to run `archiver` and `qa` workers in the environment

**Comment by avdata99** [comment]
Moved to blocked since we are not able to QA them until we finish [Multi#417](https://github.com/GSA/datagov-ckan-multi/issues/417) and  [Deploy#2123](https://github.com/GSA/datagov-deploy/issues/2123)

**Comment by thejuliekramer** [comment]
Going to run these processed manually in staging

**Comment by thejuliekramer** [comment]
This can be moved to done because https://github.com/GSA/datagov-ckan-multi/issues/391 is ready for QA
