### ISSUE TITLE
BUG: Collections Children Datasets Not Harvesting

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/catalog.data.gov#70]
## How to reproduce

1. Harvest a collection of datasets like from a harvest source like [http://www.opm.gov/data.json](http://www.opm.gov/data.json). Click on a collection like  [this one](https://catalog-next.sandbox.datagov.us/dataset/type-of-retirement-distribution-by-number-added-to-the-retirement-roll), try and view datasets within the collection - there are none.

Catalog: https://admin-catalog.data.gov/dataset/annual-performance-reports-aprs

Sandbox: https://catalog-next.sandbox.datagov.us/dataset/annual-performance-reports-aprs

## Expected behavior

You click on **Search datasets within this collection** within a collection and should be able to see the children datasets like this [one](https://admin-catalog.data.gov/dataset?collection_package_id=e41784d0-2078-42c2-956c-2fea766bff7f) 

## Actual behavior

When you click **Search datasets within this collection** within a collection you see a page with 0 datasets like this [one](https://catalog-next.sandbox.datagov.us/dataset?collection_package_id=a5070099-aee4-4697-8f08-20ca38be8e3d)

**Comment by avdata99** [comment]
Probably related to #41

**Comment by avdata99** [comment]
Not able to reproduce the error
![image](https://user-images.githubusercontent.com/3237309/88543414-4aa95980-cfee-11ea-8d62-55a2d4e08e0f.png)

The children are visible.
I'll add a test case here.

**Comment by adborden** [comment]
Looks good, re-ran the [OPM JSON harvest](https://catalog-next.sandbox.datagov.us/harvest/admin/e5e47dce-d4a2-4a4c-8aec-b58dbb925957) and now seeing [8 datasets](https://catalog-next.sandbox.datagov.us/dataset?collection_package_id=a5070099-aee4-4697-8f08-20ca38be8e3d).

![screencapture-catalog-next-sandbox-datagov-us-dataset-2020-07-30-11_24_49](https://user-images.githubusercontent.com/509703/88959789-6bc0b300-d257-11ea-90df-b974bf51b7a9.png)
