### ISSUE TITLE
For catalog.data.gov, use async (gevent) worker model for gunicorn 

### ISSUE THREAD

**Issue by woodt** [GSA/catalog.data.gov#88]
Testing on inventory demonstrated that we want to use async workers with gunicorn.

See https://github.com/GSA/datagov-deploy/pull/1923

**Comment by danmayol** [comment]
Coworked with Tom and discussed (looked at configs, etc.). Created branch to test the changes in sandbox environment during our next cowork session.

**Comment by avdata99** [comment]
I QA this in the sandbox. It's ok
