### ISSUE TITLE
Bug: Strategy Testing Multiple Versions of CKAN in Extensions

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/catalog.data.gov#91]
We need a long term strategy for testing multiple versions of CKAN in the extensions

**Comment by adborden** [comment]
@thejuliekramer and @avdata99 recommended that we create a canonical script for CI setup under version control so at least in the near term the different extensions are running in an identical CI environment. This would replace the [travis-build.bash](https://github.com/GSA/ckanext-geodatagov/blob/master/bin/travis-build.bash) scripts.

**Comment by avdata99** [comment]
@adborden @thejuliekramer I started a proposal as a canonical script: https://github.com/GSA/catalog.data.gov/pull/145
(still require final changes)

**Comment by woodt** [comment]
OK, I've confirmed that these changes have all been merged, and the new script is running in the CI pipeline for ckanext-datajson, and succeeds.
