### ISSUE TITLE
Sitemap Generation Failure

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/catalog.data.gov#990]
Workflow with Issue: 4 - Automated CKAN Jobs
Job Failed: ckan-auto-command
CKAN Command (in question): ckan geodatagov sitemap-to-s3
CKAN Command Schedule: 0 2 * * *
Cloud.gov Environment: prod

Last Commit: 27d8e6e9612e3674cc305bd330ca3a6ca0b63212
Number of times run: 1
Last run by: nickumia-reisys
Github Action Run: https://github.com/GSA/catalog.data.gov/actions/runs/5594487267

## How to reproduce

1. `cf run-task catalog-gather --command "ckan geodatagov sitemap-to-s3" --name "sitemap-test" -m 3000M -k 2G`

## Expected behavior

Run Successful

## Actual behavior

Out of memory

## Sketch

TODO

**Comment by jbrown-xentity** [comment]
cloud.gov blip, closing.

**Comment by nickumia-reisys** [comment]
Failed to build sitemap last night, not sure how it ran out of memory... ?

![image](https://github.com/GSA/catalog.data.gov/assets/85196563/207f1319-d1cc-4ea3-a024-76c94cc1f894)

**Comment by nickumia-reisys** [comment]
@robert-bryson The Sitemap failed to create last night too.  We should probably increase the amount of memory allocated for that action?  We should test the amount that it needs to run (by manually running it testing with different values).  @GSA/data-gov-team

**Comment by nickumia-reisys** [comment]
The command fails at the 16th sitemap with `2.5G` allocated.  The command fails at the 16th sitemap with `3G` allocated.  It would seem that there is no real benefit to adding more memory.  I believe the code needs to be modified so that it frees up memory once a sitemap is generated?  Investigation/Testing needs to be done on the correct solution.

**Comment by nickumia-reisys** [comment]
Scratch that `filprofiler` is not supported in `alpine`.. switching to `memray`

**Comment by nickumia-reisys** [comment]
Summary of testing completed:
- New algorithm runs fine with `2G` on staging (10k file size)
- New algorithm fails at 16th sitemap file on prod with `2G` (10k file size)
- New algorithm succeeds on prod with `3G` (10k file size)
- New algorithm fails on prod with `2500M` (10k file size)
- New algorithm succeeds on prod with `2G` (5k file size)
- The problem was isolated to the `GeoPackageSearchQuery.get_paginated_entity_name_modtime` function in `ckanext/geodatagov/search.py`
- Testing data size on solr (prod):
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=0` (215M)
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=10000` (235M)
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=20000` (304M)
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=30000` (445M)
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=40000` (624M)
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=160000` (630M)
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=300000` (392M)
  - The size of each call was consistent no matter the order.  But it's weird that it was failing at `160k` and not `40k' but they are about the same size in memory.

**Comment by nickumia-reisys** [comment]
Successfully deployed to prod.  We'll see if sitemap update works tonight ☘️

**Comment by nickumia-reisys** [comment]
@jbrown-xentity I think we are already doing that? And maybe the screenshot below shows that?

![image](https://github.com/GSA/catalog.data.gov/assets/85196563/a026605f-b649-43fc-98f9-6a3db17b1725)


This is the code that does the solr call... (I think that it's only pulling the `'name,metadata_modified'` fields
- https://github.com/GSA/ckanext-geodatagov/blob/c013828a2a0ce047113d5ae9fd34e5681491f22a/ckanext/geodatagov/search.py#L45

**Comment by jbrown-xentity** [comment]
I stand corrected. I don't know what 10k URL's and timestamps is 630MB (that's 60 kb per URL and timestamp, seems like a lot), but 🤷‍♂️

**Comment by nickumia-reisys** [comment]
Sitemap successfully generated 🥂 
- https://github.com/GSA/catalog.data.gov/actions/runs/5687479387/job/15415913204

![image](https://github.com/GSA/catalog.data.gov/assets/85196563/d93910c7-571d-4e01-b0ca-5116cdf5415b)
![image](https://github.com/GSA/catalog.data.gov/assets/85196563/5562a888-1ad6-4d3b-aabe-de6f4d289306)

**Comment by nickumia-reisys** [comment]
Re-opening this since it has returned (having failed the last three days)
- https://github.com/GSA/catalog.data.gov/actions/runs/5988327002/job/16243393141
- https://github.com/GSA/catalog.data.gov/actions/runs/5994785181/job/16256863241
- https://github.com/GSA/catalog.data.gov/actions/runs/5982221277

> https://github.com/GSA/ckanext-geodatagov/blob/c013828a2a0ce047113d5ae9fd34e5681491f22a/ckanext/geodatagov/search.py#L45
⬆️ Code block to investigate

Tentative sketch:
- [ ] Investigate how long the solr query is from the python code.
  - [ ] Create ckan instance locally with some data (or use development).
  - [ ] Debug and/or print out the size of the solr query.
  - [ ] If the query is large, optimize it to just get the relevant data.
    - NOTE: see below, use `fl` instead of `fields`?
  - [ ] If the query is small, then the solr query is not the issue (unlikely).
- [ ] If solr is not the issue, figure out why the code is running out of memory.

Supporting Queries for reference (10k records at row=160000):
- Full records: 312.47M
  - `/solr/ckan/select?fq=state%3A%20active&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=160000`
- `fl=id`: 605.80K
  - `/solr/ckan/select?fq=state%3A%20active&fl=id&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=160000`
- `fl=id,metadata_created`: 1.12M
  - `/solr/ckan/select?fq=state%3A%20active&fl=id,metadata_created&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=160000`
- `fields=name,metadata_modified`: 312.48M
  - `/solr/ckan/select?fq=state%3A%20active&fields=name,metadata_modified&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=160000`
- `fields=id`: 312.48M
  - `/solr/ckan/select?fq=state%3A%20active&fields=id&indent=true&q.op=OR&q=*%3A*&rows=10000&sort=metadata_created%20asc&start=160000`

⭐ ⭐ High priority since this effects google search engine stuff. ⭐ ⭐

**Comment by nickumia-reisys** [comment]
Sitemap has been successfully fixed with
- https://github.com/GSA/ckanext-geodatagov/pull/268
- https://github.com/GSA/catalog.data.gov/pull/1045
- https://github.com/GSA/catalog.data.gov/actions/runs/6025376546/job/16345945244

Action runs with 10k page size with 2G of RAM without issue in <4min.
